export const hardcodedGuide = [
  {
    id: "0KJYGSTWvVKpXHXizktO",
    carb: 15,
    item: "خبز أبيض توست",
    tags: ["الخبز والنشويات"],
    qty: "شريحة",
  },
  {
    id: "0SKPElzpMrc7HXW1xm08",
    tags: [],
    qty: "كوب (٥ ملاعق طعام) ⅓",
    carb: 25,
    item: "مكرونة",
  },
  {
    id: "0ZLvpn4J9d3AeHTEZkX8",
    carb: 15,
    tags: ["الخبز والنشويات"],
    qty: "أصبعين",
    item: "شابوره",
  },
  {
    id: "0ZwO8qoYueMG8JMeF0RN",
    item: "برتقال",
    carb: 15,
    qty: "ثمرة متوسطة",
    tags: [],
  },
  {
    id: "0cHB78oKTvqsph1ILz37",
    carb: 15,
    tags: ["الفواكه"],
    item: "مانجو صغير",
    qty: "نصف ثمرة",
  },
  {
    id: "0geW2F7gIgXyAUTgOwym",
    qty: "نصف",
    item: "فطيرة رقيقة انكليزية",
    tags: ["الخبز والنشويات"],
    carb: 15,
  },
  {
    id: "0pvtDqOEOfBqJIyPcVqN",
    qty: "شريحة / ثمن بيتزا متوسطة الحجم",
    item: "بيتزا مجمدة سميكة",
    tags: ["المأكولات العامة"],
    carb: 30,
  },
  {
    id: "1Aw8GjfC6Ksbh1e4rrkc",
    carb: 15,
    qty: "شريحة",
    tags: ["الخبز والنشويات"],
    item: "خبز توست",
  },
  {
    id: "1RKqcNTWZb1PmsVHVoLF",
    item: "برتقال اليوسفي المعلب",
    qty: "ثلاث أرباع ك",
    tags: ["الفواكه"],
    carb: 15,
  },
  {
    id: "1nAeKLOA37RxBjaEvSvP",
    item: "ريس كرسبي",
    qty: "كوب ونصف",
    tags: ["الحبوب"],
    carb: 13,
  },
  {
    id: "1odTxCHidrhSp5BkX238",
    item: "بطاطس نورتيلا (شرائح)",
    tags: ["الوجبات الخفيفة والمكسرات"],
    qty: "١٥ - ٢٠ حبة",
    carb: 15,
  },
  {
    id: "1ohVnVQT6ScTZPgswr26",
    tags: ["الحلويات والكيك"],
    carb: 15,
    item: "شيره عادية",
    qty: "ملعقة كبيرة",
  },
  {
    id: "1rpfmENsG1nJw72BsZpe",
    qty: "٢٠٠ مل",
    carb: 8.6,
    item: "شوربة العدس",
    tags: [],
  },
  {
    id: "1uTZb0VQxdw6jV6PuHQc",
    tags: ["المأكولات العامة"],
    qty: "قطعتان",
    carb: 15,
    item: "فطائر سبانخ",
  },
  {
    id: "24hu123IIOMACnYELob8",
    item: "تمر هندي",
    tags: ["الفواكه", "المربى"],
    carb: 15,
    qty: "ربع كوب",
  },
  {
    id: "2DnxQXkka732VKiQWU0g",
    tags: [],
    qty: "صحن واحد",
    carb: 40,
    item: "صحن سمك وبطاطس مقلي",
  },
  {
    id: "2HrH6MmltQrU7bNywfcS",
    qty: "كوب وربع أو شريحة ١٠ أونس",
    item: "بطيخ",
    tags: ["الفواكه"],
    carb: 15,
  },
  {
    id: "2KcxcHx8xGUV5dQWgQzP",
    tags: [],
    qty: "قطعة متوسطة",
    item: "كعك براونيز",
    carb: 20,
  },
  {
    id: "2L16vZbOV4mgKMMhkdxu",
    carb: 15,
    tags: [],
    item: "بطاطس مقلية",
    qty: "١٠ - ١٥ حبة",
  },
  {
    id: "2RwlDOWF4SbOgdyt2suM",
    carb: 15,
    tags: ["البقوليات"],
    qty: "معلقتا طعام",
    item: "حمص بالطحينة",
  },
  {
    id: "2WuKgvblIOhhmZQ4ihoS",
    tags: ["الخضر غير النشوية"],
    carb: 5,
    item: "لفت",
    qty: "نصف كوب مطبوخ أو كوب واحد غير مطبوخ",
  },
  {
    id: "2X4JjbukNcdl6uofxpox",
    tags: ["الخضر غير النشوية"],
    qty: "نصف كوب مطبوخ أو كوب واحد غير مطبوخ",
    item: "فاصولياء خضراء",
    carb: 5,
  },
  {
    id: "2hUD9pX2IXxZrdhTB2Fn",
    carb: 5,
    item: "سبانخ",
    tags: ["الخضر غير النشوية"],
    qty: "نصف كوب مطبوخ أو كوب واحد غير مطبوخ",
  },
  {
    id: "2qQIzvDxEetH8LKjofAW",
    qty: "نصف كوب (٤ أونس)",
    tags: ["الحليب ومشتقاته"],
    carb: 15,
    item: "زبادي مجمد",
  },
  {
    id: "3K3Vq2m4jwvG76w3RJ0V",
    carb: 22,
    item: "كيلوقز - نخالة",
    qty: "نصف كأس",
    tags: ["الحبوب"],
  },
  {
    id: "3PlnQWlk5NRSgXYbp2WH",
    qty: "١٠٠ مل",
    carb: 6,
    tags: ["أصواص المكرونة"],
    item: "أرابياتا قليل الدسم",
  },
  {
    id: "3Y3YVNzIUo4JqTrzlLuZ",
    qty: "",
    tags: ["دهني"],
    item: "بيض مقلي",
    carb: 0,
  },
  {
    id: "3nIEkvvUp995eEoHtIIu",
    item: "توست",
    tags: [],
    qty: "شريحة",
    carb: 15,
  },
  {
    id: "405MYsrQBIYMegWbnr2t",
    item: "فطيرة لوزين بالجبن",
    carb: 23,
    qty: "قطعة واحدة",
    tags: [],
  },
  {
    id: "4CM4x4LKR5SpxSMBFQQr",
    tags: [],
    qty: "قطعة متوسطة",
    item: "سمبوسك لحم أو دجاج",
    carb: 13,
  },
  {
    id: "4UR3MygNmyuIJNrAeYPn",
    carb: 22,
    tags: [],
    qty: "إصبعان",
    item: "كندر بوينو",
  },
  {
    id: "4eOPR8g4BpcZuSnUS1od",
    qty: "كأس واحدة",
    carb: 72,
    item: "الأرز الإسباني",
    tags: ["الأرز والمعكرونة"],
  },
  {
    id: "4gRfwsxuFkDtm9mrUJaQ",
    carb: 30,
    qty: "قطعة واحدة",
    tags: ["الأرز والمعكرونة"],
    item: "الارانيا ٣ × ٤ بوصة",
  },
  {
    id: "4lT4lb62JRcSXiOxf9Cc",
    item: "لقيمات",
    tags: [],
    carb: 15,
    qty: "قطعتان",
  },
  {
    id: "50wwUBcfMDzIX0LA6GWF",
    qty: "قطعتان",
    tags: [],
    item: "شابورة",
    carb: 15,
  },
  {
    id: "57fD5CTtOC1pGE6im35z",
    qty: "نصف كوب مطبوخ أو كوب واحد غير مطبوخ",
    carb: 5,
    tags: ["الخضر غير النشوية"],
    item: "خيار",
  },
  {
    id: "58qGw4A23hf2HvAOSMVm",
    item: "شاورما دجاج",
    qty: "سندوتش متوسط",
    carb: 30,
    tags: [],
  },
  {
    id: "5Ld1lz8wtrDDT8xgLPKc",
    carb: 1.2,
    item: "تارتار صوص",
    qty: "ملعقة طعام",
    tags: ["الصلصات - الأصواص - الشوربات"],
  },
  {
    id: "5N4UCeBRsnZ1DJUJ2mCF",
    qty: "ملعقة كبيرة",
    item: "سكر",
    carb: 15,
    tags: ["الحلويات والكيك"],
  },
  {
    id: "5W4SpZyVnksqajYbNWSo",
    item: "لبن منزوع الدسم",
    tags: ["الحليب ومشتقاته"],
    carb: 15,
    qty: "ثلاث أرباع كوب",
  },
  {
    id: "5qfe6HOAickBfx2yQOq6",
    tags: ["الخبز والنشويات"],
    item: "تاكو شيل",
    qty: "٢ بحجم ٦ بوصات عرض",
    carb: 15,
  },
  {
    id: "5qxtry41IKUl98UzTMf5",
    carb: 9,
    tags: [],
    qty: "٣ قطع",
    item: "ناغيت دجاج",
  },
  {
    id: "5u5Yyos2jk8ZKUYA0o3F",
    carb: 15,
    item: "عنب",
    tags: [],
    qty: "١٥-١٧ حبة",
  },
  {
    id: "5zclebXBap12tUZHGJCo",
    tags: ["الفواكه"],
    qty: "نص فاكهة (٨ أونس) كأس واحدة",
    item: "البابايا",
    carb: 15,
  },
  {
    id: "6RetNuFCh3ov9JUKofI1",
    qty: "ملعقة طعام (١٥ غرام)",
    tags: [],
    item: "صوص باربكيو",
    carb: 2,
  },
  {
    id: "6XOdHtqkxsPAqNb5zGXb",
    tags: ["الحلويات والكيك"],
    carb: 15,
    item: "حلوى البودينج (خالية من السكر)",
    qty: "نصف كوب",
  },
  {
    id: "6YLaaCunInUePVtvN4cL",
    tags: ["الخبز والنشويات"],
    carb: 7,
    item: "كراكرز ماتزو",
    qty: "حبة",
  },
  {
    id: "6oU7ebBci0IQrPZHvdVg",
    qty: "رزمة واحدة",
    tags: ["البقوليات"],
    item: "دقيق الشوفان، جاهز، بنكهة",
    carb: 30,
  },
  {
    id: "761ltC7b3KBN0dUYVsWy",
    qty: "٢ بوصة مربعة",
    tags: ["الحلويات والكيك"],
    item: "براونيز شوكولاتة",
    carb: 30,
  },
  {
    id: "78dcf2nVBlbzM3W4E09p",
    item: "جوز الهند مسحوق",
    qty: "كأسان",
    carb: 15,
    tags: ["الخضر النشوية"],
  },
  {
    id: "7D7egAm00uQ6e8vzIwpj",
    qty: "ملعقتي طعام (٢٨ مل)",
    tags: [],
    carb: 12,
    item: "حليب مكثف محلى",
  },
  {
    id: "7DKJ6zeOL7SrPX3zVtY1",
    qty: "ربع قطعة من الحجم الكبير",
    tags: ["المأكولات العامة"],
    item: "مناقيش زعتر",
    carb: 15,
  },
  {
    id: "7NPGWatRfsVYjJSdzMAN",
    carb: 15,
    item: "خبز قليل الدسم",
    qty: "رغيفان",
    tags: ["الخبز والنشويات"],
  },
  {
    id: "7RX4yLdSeUgIWAkd6tML",
    carb: 15,
    tags: ["البقوليات"],
    qty: "نصف كأس",
    item: "الشوفان",
  },
  {
    id: "7SuQKJPOXAhMIZzh6m7p",
    tags: ["الوجبات الخفيفة والمكسرات"],
    carb: 15,
    item: "الفشار مشوي",
    qty: "٣ أكواب",
  },
  {
    id: "7WsjI9Zd34iY34WjelJE",
    tags: [],
    item: "مناقيش زعتر حجم كبير",
    qty: "¼",
    carb: 15,
  },
  {
    id: "7cVjCr63nyI5ElYw6GiX",
    carb: 15,
    qty: "كوب",
    tags: [],
    item: "توت أحمر",
  },
  {
    id: "7qZ0Wgs5VVME513Ls0hb",
    carb: 56,
    qty: "رغيف واحد",
    tags: [],
    item: "خبز مصري",
  },
  {
    id: "7rsJQWVKdEZvr60bl0bn",
    carb: 15,
    qty: "نصف كوب",
    tags: ["الفواكه", "المربى"],
    item: "جيلاتين طبيعي",
  },
  {
    id: "83KMaC7M4jAADvoYf5Qp",
    qty: "كوب واحد أو شريحة ١٠ أونس",
    carb: 15,
    item: "شمام",
    tags: ["الفواكه"],
  },
  {
    id: "83UlUXvPInXDkZEf9sf3",
    tags: [],
    carb: 15,
    qty: "٢-٣ قطع",
    item: "بسكويت بالزبدة",
  },
  {
    id: "89KJPjryOxr7Y0u3tKdg",
    item: "إندومي",
    qty: "نصف كوب",
    carb: 15,
    tags: ["الأرز والمعكرونة"],
  },
  {
    id: "8AOTGtt67W0ox9fG2Sln",
    item: "طبق معكرونة",
    qty: "كوب",
    tags: [],
    carb: 69.4,
  },
  {
    id: "8EHGuWGo5yaA01dqdsi2",
    carb: 15,
    item: "مشمش",
    qty: "٤ ثمرات",
    tags: [],
  },
  {
    id: "8IOSJIgTmcTmhlQAg7Zs",
    item: "بطاطس مقلي / مشوي",
    qty: "عود واحد",
    carb: 1,
    tags: [],
  },
  {
    id: "8IyJEyd3oryKkZG19CPF",
    qty: "كأس واحدة",
    tags: [],
    carb: 1.3,
    item: "حليب الصويا",
  },
  {
    id: "8JaX17msGotd9l1hCdDS",
    tags: ["الحلويات والكيك"],
    qty: "قطعة واحدة (٦٠ غرام)",
    carb: 30,
    item: "سكون",
  },
  {
    id: "8NqpmItgafFSafOMeh71",
    item: "تورتيليني",
    carb: 20,
    tags: ["الأرز والمعكرونة"],
    qty: "نصف كأس",
  },
  {
    id: "8W9lCGMCvl4gBDqi0oyA",
    item: "خبز عربي صغير",
    tags: ["الخبز والنشويات"],
    carb: 15,
    qty: "نصف",
  },
  {
    id: "8e37aSVOxcGV1JA2KBd6",
    qty: "لوح واحد (٤٦ غرام)",
    carb: 25,
    tags: [],
    item: "جالاكسي",
  },
  {
    id: "8xxS8F6UseWkeB24MQAG",
    item: "صوص الباربيكيو",
    qty: "ملعقة طعام",
    carb: 4,
    tags: ["الصلصات - الأصواص - الشوربات"],
  },
  {
    id: "8zU4rRUuUzoUsdlut6gT",
    tags: ["الفواكه"],
    qty: "نصف",
    carb: 15,
    item: "كمثرى كبيرة",
  },
  {
    id: "9DBGLkvmrSuD2I7rHP2Y",
    qty: "ثمرة متوسطة",
    item: "تفاح",
    tags: [],
    carb: 15,
  },
  {
    id: "9Ssb9SgWxLr8e6HHn0wO",
    tags: [],
    qty: "٣-٤ حبات",
    carb: 15,
    item: "كستناء",
  },
  {
    id: "9WBGHLemQ7VKmchb6xMC",
    carb: 15,
    tags: ["الأرز والمعكرونة"],
    item: "الفشار",
    qty: "٣ كؤوس",
  },
  {
    id: "9XvtlC4S5XEAd7DNOEHw",
    qty: "قطعة متوسطة",
    tags: [],
    item: "خبز صامولي",
    carb: 25,
  },
  {
    id: "9m8QA2ZhCiIk0zY3T2kT",
    qty: "رغيف",
    item: "تورتيلا كبير جدا",
    carb: 60,
    tags: ["الخبز والنشويات"],
  },
  {
    id: "9maLglO21LO81dt7PTMA",
    tags: ["الوجبات الخفيفة والمكسرات"],
    carb: 45,
    qty: "شطيرة واحدة",
    item: "ساندوتش دجاج مغطى بالخبز",
  },
  {
    id: "9oxjlX66STeluXMyT60e",
    tags: [],
    qty: "قطعة متوسطة",
    item: "كب كيك",
    carb: 30,
  },
  {
    id: "9q8Xz1Sg73dAclD8QDDj",
    item: "بسكويت سويتز صغير",
    qty: "١٥ قطعة",
    tags: ["الوجبات الخفيفة والمكسرات"],
    carb: 15,
  },
  {
    id: "9sxgpioH7RSbMkKdqTNK",
    item: "برغر بالجبن",
    qty: "متوسط الحجم",
    carb: 30,
    tags: [],
  },
  {
    id: "A0zNTXCX8zizdFSgihoC",
    tags: [],
    item: "حليب خالي الدسم",
    qty: "كوب ٢٤٠ مل",
    carb: 12,
  },
  {
    id: "A5JzSFus98gO2TiJOGVB",
    qty: "ملعقة طعام",
    item: "متبل",
    tags: [],
    carb: 2,
  },
  {
    id: "ACD60QwB8zY3RLOa01da",
    carb: 15,
    tags: ["الفواكه"],
    item: "برقوق صغير",
    qty: "ثمرتان",
  },
  {
    id: "AEv22UgVxIxkrOYdWhuM",
    item: "كيلوقز عسل",
    qty: "نصف كأس",
    carb: 17,
    tags: ["الحبوب"],
  },
  {
    id: "Af1EfKTDUY6PRx8D1bpB",
    tags: ["الفواكه"],
    carb: 15,
    item: "كرز (حلو، طازج)",
    qty: "نصف كأس",
  },
  {
    id: "BFbXOK9BKqnPjlCJp1ZS",
    qty: "ثلاث أرباع كأس",
    carb: 15,
    tags: ["الحبوب"],
    item: "الحبوب الجاهزة للأكل",
  },
  {
    id: "BZZWbfIZoWGdlTIrsN0c",
    qty: "قطعة واحدة",
    carb: 32,
    item: "مافن صغيرة",
    tags: ["الحلويات والكيك"],
  },
  {
    id: "BzNXyjAA89OdCYlQEiAn",
    item: "الحلويات (توكس، قالكسي، مارس، سينكرز)",
    tags: ["الحلويات والكيك"],
    qty: "٢٥ غرام",
    carb: 25,
  },
  {
    id: "C7QbD1dJCcHrICuWuJvm",
    carb: 15,
    fiber: 3,
    item: "الكسكس",
    tags: ["الأرز والمعكرونة"],
    qty: "ثلث كأس",
  },
  {
    id: "CIMe3CqHXuGKvpIsIdsh",
    item: "بولو",
    qty: "٢٥ غرام",
    carb: 25,
    tags: ["الحلويات والكيك"],
  },
  {
    id: "CXSdS1tcD3VWC4gdrT59",
    tags: ["الحليب ومشتقاته"],
    qty: "علبة واحدة",
    carb: 25,
    item: "لبن زبادي المراعي غير المخلوط",
  },
  {
    id: "CbzyV3aUPxFrKP5oGGiw",
    qty: "كيس ٧٥ غرام",
    item: "إندومي دجاج بالكاري",
    carb: 48,
    tags: [],
  },
  {
    id: "CpZL8PibXpkf0eVlcMoY",
    item: "إليام",
    carb: 15,
    qty: "نصف كأس",
    tags: ["الخضر النشوية"],
  },
  {
    id: "DG5UvYClXfYT704WiMM3",
    carb: 5,
    tags: ["الخضر غير النشوية"],
    qty: "نصف كوب مطبوخ أو كوب واحد غير مطبوخ",
    item: "كراث",
  },
  {
    id: "DPMTBDNgcMFTbNnolus2",
    tags: ["الحبوب"],
    item: "شيروز",
    qty: "نصف كأس",
    carb: 12,
  },
  {
    id: "DSDBHaFkHrd0dAIhguPC",
    tags: ["الحلويات والكيك"],
    item: "دونت طويل بالشوكولاتة",
    qty: "قطعة واحدة",
    carb: 60,
  },
  {
    id: "DgnhFNtTdLBH4yP91iTu",
    qty: "٢-٣ قطع صغيرة",
    item: "سمبوسك",
    carb: 20,
    tags: [],
  },
  {
    id: "E72LWPQJnF8joBVriFLc",
    qty: "كوب",
    item: "كورن فلكس",
    carb: 24,
    tags: [],
  },
  {
    id: "E8WFefHOrN17KLj8hoAP",
    carb: 15,
    qty: "كأس واحدة",
    tags: ["العصائر والمشروبات"],
    item: "عصير مشكل، قليل السعرات",
  },
  {
    id: "EF79h1ifeg8PiRDf0E7l",
    qty: "قطعة متوسطة ١٣ غرام",
    item: "قراقيش",
    tags: [],
    carb: 6.83,
  },
  {
    id: "EHFpigDi2AllNGkB6uBY",
    carb: 15,
    item: "عصير تفاح",
    tags: [],
    qty: "كوب (١٢٠ مل) ½",
  },
  {
    id: "EJHa5DDVwoh7VvTo8PgI",
    item: "فاصولياء محمصة",
    tags: ["الخضر النشوية"],
    qty: "ثلث كأس",
    carb: 15,
  },
  {
    id: "F51Q7dn7h8bugK9Oyt4N",
    carb: 15,
    tags: ["البقوليات"],
    qty: "ثلث كأس",
    item: "العدس",
  },
  {
    id: "F7fZq00b2G9lU0uByhp0",
    carb: 5,
    item: "فلفل",
    qty: "نصف كوب مطبوخ أو كوب واحد غير مطبوخ",
    tags: ["الخضر غير النشوية"],
  },
  {
    id: "FdPrhcplP9Um4bEbPXrx",
    carb: 15,
    tags: ["البقوليات"],
    item: "تبولة",
    qty: "كوب",
  },
  {
    id: "Fkd2tXPy9IPkz3iDTbdN",
    qty: "نصف كأس",
    tags: ["العصائر والمشروبات"],
    carb: 15,
    item: "عصير التفاح",
  },
  {
    id: "FmVPdg8rEwK7vuC4rvZq",
    item: "ساندويتش فلافل متوسط",
    qty: "خبز عربي مفرود متوسط",
    tags: [],
    carb: 40,
  },
  {
    id: "Fxx6xtdKIHATxBwXktaI",
    tags: ["الخضر غير النشوية"],
    carb: 5,
    item: "قرنبيط",
    qty: "نصف كوب مطبوخ أو كوب واحد غير مطبوخ",
  },
  {
    id: "G0xlCzcZ9EUKj8zRjDik",
    qty: "قرص واحد",
    item: "قرص فلافل",
    tags: [],
    carb: 5,
  },
  {
    id: "GD7TpdO83DPQbLA08les",
    carb: 15,
    tags: ["الفواكه"],
    item: "مشمش مجفف",
    qty: "٤ ثمرات",
  },
  {
    id: "GKvygXOOX7obIviv7tiY",
    carb: 30,
    qty: "قطعة متوسطة",
    tags: [],
    item: "خبز برغر",
  },
  {
    id: "GUfydI45jw3KkLDKxOVc",
    item: "فطيرة بالسكر",
    carb: 17.61,
    tags: ["عُدّ 5 مرات"],
    qty: "قطعة واحدة ٥٠غ",
  },
  {
    id: "GWFuVrhVG5BMzi2JEoFz",
    carb: 2.5,
    item: "صوص بولونيس",
    tags: [],
    qty: "١٠٠ مل",
  },
  {
    id: "GfJSrG8hicTLK3ZdYIoG",
    item: "جوز الهند",
    carb: 15,
    tags: ["الخضر النشوية"],
    qty: "ربع كوب",
  },
  {
    id: "GvDR5z8Ol7dT5tf2ncpq",
    tags: ["العصائر والمشروبات"],
    item: "عصير برتقال",
    qty: "نصف كأس (١٢٠ مل)",
    carb: 15,
  },
  {
    id: "H0pPF92OnHgmWDZtjDYm",
    tags: ["المأكولات العامة"],
    qty: "شريحة / ثمن بيتزا متوسطة الحجم",
    item: "بيتزا مجمدة رقيقة",
    carb: 15,
  },
  {
    id: "HN4oDabpNjqHHwExvk14",
    qty: "٤ ثمرات",
    carb: 15,
    item: "مشمش طازج",
    tags: ["الفواكه"],
  },
  {
    id: "HTaoiqwGLgcVfXfpmU4y",
    qty: "٢٤ حبة",
    item: "مكسرات أويستر",
    carb: 15,
    tags: ["الوجبات الخفيفة والمكسرات"],
  },
  {
    id: "HjjG3QXv2y6NmP7Qxqbc",
    carb: 5,
    tags: [],
    qty: "كوب",
    item: "قنبيط",
  },
  {
    id: "HshuIHk2BPHGcW2b77Rw",
    qty: "ثلث كأس",
    tags: ["العصائر والمشروبات"],
    carb: 15,
    item: "عصير العنب",
  },
  {
    id: "Hv5HBEUge3qWUX2rUaM2",
    tags: ["أصواص المكرونة"],
    carb: 15,
    qty: "كأس واحدة",
    item: "شوربة الكريمة",
  },
  {
    id: "I9BDmXU56cMwxovFE3hL",
    carb: 26,
    tags: [],
    item: "خبز فرنسي",
    qty: "رغيف صغير",
  },
  {
    id: "IHpu0h9u6774Q5JUXgiE",
    carb: 15,
    tags: [],
    item: "عصير كوكتيل",
    qty: "كوب (٨٠ مل) ⅓",
  },
  {
    id: "ILLHazRErVOXpfrqVJl4",
    carb: 15,
    qty: "قطعة صغيرة",
    item: "وافل",
    tags: ["الحلويات والكيك"],
  },
  {
    id: "IRfrn2KeMWLL5MymgSNN",
    item: "طبق أرز أبيض",
    carb: 66.25,
    tags: [],
    qty: "كوب وربع",
  },
  {
    id: "ISEa9un4CJliwBm491lN",
    qty: "½ كوب",
    tags: [],
    item: "عدس",
    carb: 18,
  },
  {
    id: "IXCQQxmQlFFV7VAqxRka",
    qty: "نصف كوب مطبوخ أو كوب واحد غير مطبوخ",
    tags: ["الخضر غير النشوية"],
    carb: 5,
    item: "باميه",
  },
  {
    id: "IXw9i3QLxRFiLIQlIGug",
    tags: ["الخبز والنشويات"],
    item: "بان كيك",
    carb: 20,
    qty: "قطعة واحدة",
  },
  {
    id: "IZhebxTIog5RJQarkRza",
    carb: 35.7,
    tags: ["الحلويات والكيك"],
    item: "Biskrem",
    qty: "عبوة ٨ قطع (~٦٠ غرام)",
  },
  {
    id: "IjPiWHGqfBtMKlWY15Zz",
    tags: ["الفواكه", "المربى"],
    carb: 14,
    item: "رطب",
    qty: "٤ حبات",
  },
  {
    id: "J0qmN3k0rEIpoiFWSSBU",
    item: "جرانولا",
    tags: ["الوجبات الخفيفة والمكسرات"],
    qty: "ربع كأس",
    carb: 15,
  },
  {
    id: "J4FngL17zRY46TnV80in",
    item: "خبز بالزبيب",
    carb: 15,
    qty: "رغيف",
    tags: ["الخبز والنشويات"],
  },
  {
    id: "J6Xcn641dY7AH7MOg6D2",
    tags: ["الحليب ومشتقاته"],
    qty: "نصف كأس",
    carb: 15,
    item: "كاسترد",
  },
  {
    id: "J8WdXJ4lyMjtUxeaoWtW",
    qty: "٦ ملاعق",
    carb: 27,
    item: "مندي",
    tags: ["الأرز والمعكرونة"],
  },
  {
    id: "JQEdrjHAF0d056qVY5wr",
    qty: "واحدة",
    item: "جرانولا بار أصابع",
    carb: 15,
    tags: ["الوجبات الخفيفة والمكسرات"],
  },
  {
    id: "KBRGhcMZnIfA4zJ3QE2n",
    carb: 15,
    item: "أناناس معلب",
    tags: ["الفواكه"],
    qty: "نصف كأس = ثلاث شرائح متوسطة",
  },
  {
    id: "KQYw8ivKtSyr8kk0kBqB",
    qty: "½ كوب",
    carb: 15,
    item: "شوفان مطبوخ",
    tags: [],
  },
  {
    id: "Kf1P2qqC5D77rCrtvk4P",
    item: "عسل",
    carb: 15,
    qty: "ملعقة طعام",
    tags: [],
  },
  {
    id: "Kh4C5NUihPlv1mPlZlYu",
    qty: "كوب واحد",
    item: "معكرونة بالجبن",
    tags: ["الأرز والمعكرونة"],
    carb: 45,
  },
  {
    id: "Km2ctXTqhwsl0kgxgq1z",
    item: "خوخ",
    tags: ["الفواكه"],
    qty: "ثمرة متوسطة",
    carb: 12,
  },
  {
    id: "Kzc5IBSxXcYxN3w6HLTW",
    item: "ملك شايك",
    carb: 15,
    tags: ["الحليب ومشتقاته"],
    qty: "ربع كأس",
  },
  {
    id: "L5ZBIXGsEaO8Oz5vz3vj",
    item: "كوكو بفس",
    carb: 13,
    tags: ["الحبوب"],
    qty: "نصف كأس",
  },
  {
    id: "LEUSXrOKeQfynd1gCgMj",
    carb: 15,
    qty: "نصف كأس",
    item: "بران بالعسل",
    tags: ["الحبوب"],
  },
  {
    id: "LJxe80lYrHs2jCIOYWkX",
    qty: "٣٣٠ مل",
    item: "كولا عادي",
    carb: 35,
    tags: ["العصائر والمشروبات"],
  },
  {
    id: "LXaDA7XX2oUfOdl2vlYY",
    qty: "٢٠٠ مل",
    tags: ["أصواص المكرونة"],
    carb: 21,
    item: "كريمة الطماطم",
  },
  {
    id: "M5qxXBT0WzSKDwr2Ou6W",
    carb: 2.5,
    qty: "١٠٠ مل",
    tags: ["أصواص المكرونة"],
    item: "بولونيس",
  },
  {
    id: "M70DxjM6vE0Z0vmnQkXO",
    tags: ["الوجبات الخفيفة والمكسرات"],
    qty: "٨ حبات",
    carb: 15,
    item: "مكسرات مالحة",
  },
  {
    id: "MUNw06H3VpY5J4oen6mU",
    item: "بخارى",
    carb: 15,
    tags: ["الفواكه"],
    qty: "ثمرتان",
  },
  {
    id: "MmhmZFNmUGLsHPmI5d7z",
    carb: 21,
    item: "كوكيس",
    tags: ["الحلويات والكيك"],
    qty: "قطعة متوسطة (٥٥ غرام)",
  },
  {
    id: "MyWC4VnU7q0HKcqrKK8I",
    item: "دونت مدور بالشوكولاتة",
    carb: 45,
    tags: ["الحلويات والكيك"],
    qty: "قطعة واحدة",
  },
  {
    id: "NDtbeh6M7zj2Ta2FAotx",
    item: "الدقيق",
    carb: 95,
    tags: ["البقوليات"],
    qty: "كأس واحدة",
  },
  {
    id: "NIFAOdUZ63ViIgj3CpuE",
    item: "خليط من الخضر دون معكرونة أو بازلاء",
    carb: 5,
    tags: ["الخضر غير النشوية"],
    qty: "نصف كوب مطبوخ أو كوب واحد غير مطبوخ",
  },
  {
    id: "NPnTdFv9T6GKcnbH6KVa",
    carb: 15,
    item: "فطيرة محلاة",
    qty: "٤ بوصات عرض",
    tags: ["الخبز والنشويات"],
  },
  {
    id: "NTKgahrG6QuKCQm1PugG",
    item: "سميت",
    qty: "قطعة متوسطة",
    carb: 62.8,
    tags: [],
  },
  {
    id: "NXUSkNEkXrXyRlYDcthF",
    tags: ["الوجبات الخفيفة والمكسرات"],
    qty: "٣ حبات",
    item: "مكسرات كبيرة خفيفة",
    carb: 15,
  },
  {
    id: "NworOPWUsvyLN4SuszF5",
    item: "حمص",
    carb: 3,
    tags: ["البقوليات"],
    qty: "ملعقة طعام",
  },
  {
    id: "O0FKy4Icoj9INN5UAEl1",
    qty: "٦ حبات",
    item: "أصابع الدجاج المقلي",
    carb: 15,
    tags: ["المأكولات العامة"],
  },
  {
    id: "O4HK6Dg6jYUJazDGEO6O",
    carb: 23,
    item: "شراب الكاكاو مسكر",
    qty: "ظرف واحد",
    tags: ["العصائر والمشروبات"],
  },
  {
    id: "O8v2GqFvWdxwFTn6G757",
    qty: "نصف كوب مطبوخ أو كوب واحد غير مطبوخ",
    item: "فجل",
    carb: 5,
    tags: ["الخضر غير النشوية"],
  },
  {
    id: "OWXhPn8oVba7KXwKMNZP",
    qty: "٣ ملاعق",
    tags: [],
    item: "سلطة",
    carb: 2,
  },
  {
    id: "OaAEUL5QXP5TcLGAfsiS",
    tags: ["الصلصات - الأصواص - الشوربات"],
    item: "ماسترد / خردل",
    carb: 1.2,
    qty: "ملعقة شاهي",
  },
  {
    id: "OoKzyOLGSfvNspgay6O2",
    tags: ["البقوليات"],
    item: "قطع من القمح",
    carb: 15,
    qty: "نصف كأس",
  },
  {
    id: "Op8CZtqEU7ipZK3pUG9y",
    item: "صوص الدجاج",
    carb: 9,
    qty: "٢٠٠ مل",
    tags: ["أصواص المكرونة"],
  },
  {
    id: "OvYbSaOobhmZ9bxrGN8a",
    qty: "نصف كوب مطبوخ أو كوب واحد غير مطبوخ",
    item: "زهرة",
    tags: ["الخضر غير النشوية"],
    carb: 5,
  },
  {
    id: "Owz5VHirHiNQbn7aabi9",
    qty: "كأس واحدة",
    item: "قطع خبز محمص",
    tags: ["الخبز والنشويات"],
    carb: 15,
  },
  {
    id: "P1uX7HpWfzxeboTWCeW7",
    tags: ["الوجبات الخفيفة والمكسرات"],
    qty: "٦ حبات",
    item: "مكسرات مالحة مدورة",
    carb: 15,
  },
  {
    id: "PBr2bJoCeblFswc435EJ",
    item: "التوت الأزرق",
    qty: "ثلاث أرباع كأس",
    tags: ["الفواكه"],
    carb: 15,
  },
  {
    id: "PELeJeoeB1OJNiPB2fHx",
    qty: "٣٣٠ مل",
    carb: 38,
    tags: ["العصائر والمشروبات"],
    item: "عصير التفاح الفوار",
  },
  {
    id: "PGUfhJY9qsbZhiS0eLs0",
    carb: 18,
    item: "خضر مشكلة مع الذرة",
    qty: "كأس واحدة",
    tags: ["الخضر النشوية"],
  },
  {
    id: "PNZfWnCUUyLRMPNWoUab",
    item: "الأرز القصير",
    qty: "كأس واحدة",
    tags: ["الأرز والمعكرونة"],
    carb: 54,
  },
  {
    id: "Pu3S1Op2ROWkxRaVvEkG",
    qty: "٢ بوصة مكعبة",
    item: "خبز الذرة",
    tags: ["الخبز والنشويات"],
    carb: 15,
  },
  {
    id: "PuG2dChwgwk7ERrKEk3i",
    item: "معصوب",
    tags: [],
    carb: 20,
    qty: "٢-٣ ملاعق",
  },
  {
    id: "Q8DzjObmbU3LMICysPzF",
    item: "معمول",
    qty: "قُطيعَة ٤٠ غرام",
    carb: 22,
    tags: [],
  },
  {
    id: "QHVKlbb6b97dOq5SLklv",
    tags: ["الحبوب"],
    qty: "نصف كأس",
    carb: 15,
    item: "كورن فلكس العسل بالمكسرات",
  },
  {
    id: "QLpWTC4bpFrWVPWVnE29",
    carb: 15,
    item: "فشار",
    qty: "٣ أكواب",
    tags: [],
  },
  {
    id: "QNfCe4QirK9WmGRFxsl9",
    tags: ["المأكولات العامة"],
    carb: 15,
    item: "ورق عنب",
    qty: "٦ أصابع صغيرة",
  },
  {
    id: "QaekUePuzZ1kCcUB8uQb",
    carb: 3,
    item: "ليون",
    tags: ["الفواكه"],
    qty: "ثمرة واحدة",
  },
  {
    id: "R6zK55W6YiIU4siGzWNk",
    carb: 15,
    tags: [],
    qty: "¼ رغيف",
    item: "خبز بر بالنخالة",
  },
  {
    id: "RI4LUBnpUEiA1OIF5JGr",
    item: "لحم بعجين",
    tags: [],
    qty: "قطعة متوسطة",
    carb: 30,
  },
  {
    id: "RVMzAvCWjWZcLb926Pnd",
    item: "كيك شوكولاتة",
    tags: ["الحلويات والكيك"],
    qty: "وصلة متوسطة",
    carb: 42,
  },
  {
    id: "RVxfayOOWhCfoZYhQzA2",
    fiber: 3,
    item: "بطاطس مسلوقة",
    qty: "ثمرة صغيرة",
    tags: ["الخضر النشوية"],
    carb: 15,
  },
  {
    id: "RYhbRc3CHeSzyLoK5xqD",
    carb: 12,
    tags: ["الحبوب"],
    qty: "ثلاث أرباع كأس",
    item: "كيلوقز عادي",
  },
  {
    id: "RZln0U7hgG4DAdk3sp0v",
    item: "كاتشب",
    tags: ["الصلصات - الأصواص - الشوربات"],
    carb: 15,
    qty: "ربع كوب",
  },
  {
    id: "RiJ67Ut76kh5oVWs6xJG",
    item: "زبدة",
    tags: [],
    carb: 0,
    qty: "ملعقة صغيرة (٥ غرام)",
  },
  {
    id: "S3nvMORgauTqMugeYhg2",
    tags: [],
    item: "مشروب كاكاو ساخن",
    carb: 21.5,
    qty: "ظرف ٣٠ غرام",
  },
  {
    id: "S8Yko71KRqDOqvOekdVL",
    tags: ["الخضر النشوية"],
    qty: "١٠ : ١٥ عود",
    item: "بطاطس مقلية، أعواد صغيرة",
    carb: 15,
  },
  {
    id: "SFWOP6p7YazxIeAIxGJt",
    carb: 30,
    item: "كيك مجمد",
    qty: "٢ بوصة مربعة",
    tags: ["الحلويات والكيك"],
  },
  {
    id: "SYcyAv4l0Qj0HwoqMvD1",
    item: "رمان",
    carb: 15,
    tags: [],
    qty: "½ كوب",
  },
  {
    id: "TJZQ44lvx4nHVYFn20wN",
    carb: 0,
    item: "زيت زيتون",
    tags: [],
    qty: "ملعقة صغيرة (١٥ غرام)",
  },
  {
    id: "TKUJIhGSyCQcWb8Dkltq",
    item: "صوص ثوم",
    carb: 0,
    tags: [],
    qty: "ملعقة طعام (١٥ غرام)",
  },
  {
    id: "U2YCv00lU8pSjjFhjHWV",
    tags: ["الأرز والمعكرونة"],
    item: "المعكرونة، الباستا",
    qty: "نصف كأس",
    carb: 15,
  },
  {
    id: "UmBAV7xWPdp4sRWYngQy",
    item: "كريم كارميل",
    carb: 25,
    qty: "قطعة متوسطة",
    tags: [],
  },
  {
    id: "UscsHvtPVMS69QB7UYoJ",
    carb: 15,
    item: "برقوق معلب",
    tags: ["الفواكه", "المربى"],
    qty: "نصف كأس",
  },
  {
    id: "V5RYAzbogseXbEBfEEew",
    carb: 15,
    item: "سمبوسك بالجبن",
    tags: [],
    qty: "٣ قطع صغيرة",
  },
  {
    id: "VJmPFyPY4u1AVTDlOZ9e",
    item: "شوربة اللحم",
    carb: 13,
    qty: "٢٠٠ مل",
    tags: ["أصواص المكرونة"],
  },
  {
    id: "VPHIIojmpc8QAfGWhhcA",
    qty: "نصف كأس",
    item: "نسكويك",
    carb: 17,
    tags: ["الحبوب"],
  },
  {
    id: "VeMlSz7y2pViDRC5WJoE",
    carb: 15,
    tags: [],
    qty: "كوب",
    item: "توت أسود",
  },
  {
    id: "VhK11TaoUnyrNgZJeGGp",
    carb: 26,
    qty: "عبوة صغيرة",
    item: "بطاطس ماكدونالدز",
    tags: ["الخضر النشوية"],
  },
  {
    id: "VmVtvBWA52wGF0ZN7ZvI",
    item: "ساندوتش زبدة الفول السوداني والجلي العادي",
    tags: ["الوجبات الخفيفة والمكسرات"],
    qty: "شطيرة واحدة",
    carb: 45,
  },
  {
    id: "VoO1XhOtbta7RhPO128D",
    qty: "ملعقتا طعام",
    carb: 15,
    item: "زبيب",
    tags: ["الفواكه", "المربى"],
  },
  {
    id: "VuRoD35BZ6RpakpgMEXL",
    item: "عنب صغير",
    qty: "١٥ - ١٧ حبة",
    carb: 15,
    tags: ["الفواكه"],
  },
  {
    id: "VyXzjuqGCcNq7HeKY6lb",
    carb: 15,
    tags: ["العصائر والمشروبات"],
    item: "عصير أناناس",
    qty: "نصف كأس",
  },
  {
    id: "W0AmSrKIK6efUjs7EDV5",
    carb: 11,
    tags: [],
    item: "كبة كبيرة",
    qty: "قطعة واحدة",
  },
  {
    id: "WWvZpRXMQe7rSzR4FNMt",
    qty: "٢٠٠ مل",
    carb: 11,
    item: "صوص الدجاج والخضار",
    tags: ["أصواص المكرونة"],
  },
  {
    id: "Wa6yBQkNAUBCDhPRePH8",
    tags: [],
    item: "طعمية / فلافل",
    qty: "٣ أقراص متوسطة",
    carb: 15,
  },
  {
    id: "Wfy2cgETY1n8MgUeCpHy",
    tags: [],
    qty: "¼ كوب",
    item: "بليلة",
    carb: 15,
  },
  {
    id: "WzDijtdB266Gw5yh2LVO",
    carb: 15,
    item: "صلصة المكرونة",
    qty: "نصف كوب",
    tags: ["الصلصات - الأصواص - الشوربات"],
  },
  {
    id: "X1O6U74ioniRdrWkdy9u",
    item: "خبز دائري - بايجل",
    tags: ["الخبز والنشويات"],
    qty: "نصف رغيف",
    carb: 30,
  },
  {
    id: "X7g1qXl3YqOGECp3ck3r",
    carb: 13,
    qty: "رغيف صغير",
    item: "خبز شامي",
    tags: ["عُدّ 4 مرات"],
  },
  {
    id: "XKi6kqvkUKYG8ZqVAmVA",
    carb: 20,
    qty: "٢ اونس",
    item: "اكلير شوكولاتة",
    tags: ["الحلويات والكيك"],
  },
  {
    id: "XPTPjmNObSlKcfNJEG1P",
    tags: [],
    carb: 24,
    item: "كورن فلكس شوكولاتة",
    qty: "¾ كوب",
  },
  {
    id: "XYKgTzN1JXEYpoMvN2zH",
    qty: "ملعقة طعام",
    carb: 3.2,
    tags: ["الصلصات - الأصواص - الشوربات"],
    item: "خل",
  },
  {
    id: "XZ5SpJniLfyAwGff2m2v",
    qty: "قطعة واحدة",
    carb: 10,
    tags: ["دهني", "الضعف", "مُعَدَّلْ"],
    item: "رقاق",
  },
  {
    id: "Xdhc5ZRHKPoiT30owMZf",
    carb: 15,
    item: "حبوب نخالة",
    tags: ["الحبوب"],
    qty: "نصف كأس",
  },
  {
    id: "XeBzgiqdK4298nxxqKEJ",
    item: "الفول الأخضر",
    carb: 15,
    qty: "كوبان",
    tags: ["البقوليات"],
  },
  {
    id: "Xi4y3ej9Uj9dkZneE0aA",
    tags: ["الخبز والنشويات"],
    item: "خبز عربي كبير",
    carb: 15,
    qty: "ثمن",
  },
  {
    id: "Y2UYgvyhBmTAwUPEmzvm",
    tags: ["الفواكه"],
    qty: "نصف كأس",
    item: "سلطة فواكه",
    carb: 15,
  },
  {
    id: "YGW9pI0OffiLN30ikleG",
    carb: 26,
    qty: "ثمرة متوسطة",
    tags: [],
    item: "بطاطا حلوة",
  },
  {
    id: "YYMliQ0KWKsWJWyrX2I4",
    qty: "٢٠٠ مل",
    item: "كريمة المشروم",
    carb: 10,
    tags: ["أصواص المكرونة"],
  },
  {
    id: "YhoGFO1roCrEQH8XeB0P",
    carb: 15,
    tags: [],
    qty: "¼ رغيف",
    item: "خبز كعك",
  },
  {
    id: "Yl2p2FiaHJkbSWcgKa3H",
    carb: 35,
    item: "دانش بايتسري",
    tags: ["الحلويات والكيك"],
    qty: "واحدة",
  },
  {
    id: "YubcTUFDfLfjXzhso2c8",
    item: "أصابع الفاكهة المجمدة",
    tags: ["الفواكه", "المربى"],
    carb: 15,
    qty: "إصبع واحدة",
  },
  {
    id: "YwrCXrELN6AUSmNMg4Ar",
    carb: 24,
    item: "خبز تورتيلا",
    tags: [],
    qty: "شريحة متوسطة",
  },
  {
    id: "Z21rffix6VMobXGANa4P",
    tags: ["مشتقات السكر"],
    item: "Flavia Biscuits",
    qty: "كيس واحد",
    type: "edible",
    carb: 61.3,
  },
  {
    id: "Z9Eq3cLlMDqrqL5SDWV3",
    item: "تفاح مجفف",
    qty: "٤ حلقات",
    tags: ["الفواكه", "المربى"],
    carb: 15,
  },
  {
    id: "ZBMkjfvhwnYrkuW1mAWm",
    carb: 45,
    item: "ساندويتش فلافل صاج",
    qty: "خبز صاج",
    tags: [],
  },
  {
    id: "ZLmJFAg0J0isex6C8wPS",
    tags: ["الوجبات الخفيفة والمكسرات"],
    item: "لوز",
    carb: 15,
    qty: "٦٠ حبة",
  },
  {
    id: "Zqh82jvkh2cFGzgVWyDY",
    carb: 15,
    tags: ["الحليب ومشتقاته"],
    qty: "كأس واحدة",
    item: "زبادي قليل الدسم",
  },
  {
    id: "ZxyF6arq3ztAVNFoH8KR",
    carb: 15,
    tags: ["الحبوب"],
    qty: "ثلث كأس",
    item: "All Bran",
  },
  {
    id: "a68mUCaUJgBLANRskADC",
    qty: "٦ ملاعق",
    carb: 13,
    tags: ["الأرز والمعكرونة"],
    item: "هريس",
  },
  {
    id: "a8KjYxSgvkdsCUR8aCA7",
    qty: "نصف كوب مطبوخ أو كوب واحد غير مطبوخ",
    carb: 5,
    item: "كوساء",
    tags: ["الخضر غير النشوية"],
  },
  {
    id: "aHwFugaLIZuauZNue4rv",
    tags: ["الحليب ومشتقاته"],
    item: "حليب الصويا مسكر",
    carb: 6.3,
    qty: "كأس واحدة",
  },
  {
    id: "agKTiNk6eXspuQi5UQSy",
    item: "فاصولياء حمراء",
    qty: "١٠ ملاعق",
    tags: [],
    carb: 75,
  },
  {
    id: "azpZoGebSf3t3pRz5pcZ",
    carb: 25,
    item: "Ülker Finger Biscuits",
    tags: [],
    qty: "كيس واحد",
  },
  {
    id: "b6c2lib6CsOeh0BJYeh3",
    tags: ["الصلصات - الأصواص - الشوربات"],
    item: "صوص السلطة منزوع الدسم",
    carb: 15,
    qty: "ربع كوب",
  },
  {
    id: "bOZ75prB7P4dGkBSUfAX",
    tags: [],
    qty: "قطعة ونصف",
    item: "بسكويت دايجستف",
    carb: 15,
  },
  {
    id: "bVcQApxtCjgyj9cSKfi7",
    tags: [],
    carb: 24,
    item: "كرواسون لوزين بالجبن",
    qty: "قطعة واحدة",
  },
  {
    id: "bWQrwoYlr7JgrKY7BiLx",
    tags: ["الفواكه", "المربى"],
    carb: 23,
    item: "هلام التوت البري",
    qty: "ربع كأس",
  },
  {
    id: "bcd0zHbY2DzvcDeYUmCF",
    qty: "٥ قطع",
    carb: 18,
    item: "مانتو",
    tags: [],
  },
  {
    id: "bexkSdsgwJkR4xtJmojJ",
    tags: [],
    item: "صوص أربياتا قليل الدسم",
    carb: 6,
    qty: "١٠٠ مل",
  },
  {
    id: "blGzIeTn7CabmwRURYRd",
    qty: "نصف كوب مطبوخ أو كوب واحد غير مطبوخ",
    carb: 5,
    tags: ["الخضر غير النشوية"],
    item: "خرشوف",
  },
  {
    id: "bmmmVv0mhKRhfMuo2PbJ",
    qty: "ربع كوب",
    item: "شيره عادية",
    tags: ["الحلويات والكيك"],
    carb: 60,
  },
  {
    id: "buvnzyjU4e4ZynAhKFwu",
    item: "بيبسي",
    carb: 41,
    tags: [],
    qty: "علبة (٣٥٥ مل)",
  },
  {
    id: "bxEDalhnQNMBExTAStCX",
    qty: "قطعة صغيرة (⅛ رغيف)",
    tags: [],
    item: "تميس",
    carb: 15,
  },
  {
    id: "bxSFLNmhiA5pcASKumNH",
    qty: "ثمرتان",
    carb: 15,
    tags: [],
    item: "يوسفي",
  },
  {
    id: "bzoXU0L2YAIuX0Wcf4sh",
    tags: ["الحلويات والكيك"],
    carb: 15,
    item: "كيك غير متجمد",
    qty: "٢ بوصة مربعة",
  },
  {
    id: "cCZ7hWxlozDph1iRbHlM",
    qty: "ثمرتان",
    carb: 15,
    item: "تين",
    tags: ["الفواكه"],
  },
  {
    id: "cMPGWPwAoMBLtrPZef3G",
    item: "ساندويتش فلافل كبير",
    tags: [],
    carb: 60,
    qty: "خبز عربي مفرود كبير",
  },
  {
    id: "cQv02g74yABpwiuxp5Eh",
    qty: "كيس ٧٨ غرام",
    tags: [],
    carb: 40.56,
    item: "شيتوس كرنشي",
  },
  {
    id: "cSNm3QvdkC900zsS1x9w",
    carb: 15,
    qty: "٢ ونصف بوصة",
    item: "بسكويت",
    tags: ["الحلويات والكيك"],
  },
  {
    id: "cSQg3phrLYyUdR8HS8HB",
    carb: 5,
    item: "مربى الفراولة",
    qty: "ملعقة شاهي",
    tags: ["الفواكه", "المربى"],
  },
  {
    id: "camH8A0Hcqt0uJlgPLto",
    carb: 64,
    qty: "قطعة واحدة",
    tags: ["الحلويات والكيك"],
    item: "مافن كبيرة",
  },
  {
    id: "cc9c1KZVWUrX9bHe5azk",
    carb: 30,
    qty: "نصف قطعة متوسطة الحجم",
    item: "كرواسون",
    tags: ["الخبز والنشويات"],
  },
  {
    id: "cjaFuAznNFRkP7eBO4rM",
    item: "باذنجان",
    qty: "نصف كوب مطبوخ أو كوب واحد غير مطبوخ",
    tags: ["الخضر غير النشوية"],
    carb: 5,
  },
  {
    id: "d1jzSc8GQ1CBVJIYTvNh",
    item: "مخلل",
    tags: [],
    carb: 1,
    qty: "٣ عود",
  },
  {
    id: "d4Oy1VC1VW3FhUycmFk7",
    tags: [],
    qty: "١ و ½ من الحجم المتوسط",
    carb: 15,
    item: "كوساء محشية",
  },
  {
    id: "dGCg3SjM2HHSgQXoCFEq",
    tags: ["الخضر غير النشوية"],
    qty: "نصف كوب مطبوخ أو كوب واحد غير مطبوخ",
    item: "بصل",
    carb: 5,
  },
  {
    id: "dI9sKsJAlsrOcmaUJRbO",
    item: "مخلل حلو",
    carb: 2.5,
    qty: "ملعقة طعام",
    tags: ["الصلصات - الأصواص - الشوربات"],
  },
  {
    id: "dX4ZC5zTmFNsa1HJXhFn",
    tags: ["الفواكه", "المربى"],
    carb: 15,
    item: "أصابع الفاكهة",
    qty: "إصبع واحدة",
  },
  {
    id: "dgYSPMTMPe50QmuwLN85",
    qty: "٤٠ حبة",
    carb: 15,
    tags: ["الوجبات الخفيفة والمكسرات"],
    item: "كاجو",
  },
  {
    id: "dvaI4Sdu2fyMPWZ88xbf",
    carb: 15,
    item: "الموز",
    tags: ["الفواكه"],
    qty: "ثمرة صغيرة أو متوسطة",
  },
  {
    id: "dvg76cD1qtMHB54D4baY",
    carb: 1,
    item: "ثوم",
    qty: "فص واحد",
    tags: ["الخضر غير النشوية"],
  },
  {
    id: "dwHfUH9hdxb29096EjsP",
    item: "كيوي",
    tags: [],
    qty: "ثمرة متوسطة",
    carb: 15,
  },
  {
    id: "e21MDFIbz5C2Aa8aU81o",
    tags: ["الخضر النشوية"],
    item: "بطاطس مسلوق مع الجلد",
    carb: 22,
    qty: "ثمرة صغيرة",
  },
  {
    id: "e5LEz7cLOg5eJVILmrHM",
    qty: "نصف كأس",
    carb: 15,
    item: "بازلاء خضراء",
    tags: ["الخضر النشوية"],
  },
  {
    id: "e7qqxPXrcilvP9lMw8XO",
    tags: ["أصواص المكرونة"],
    item: "صوص اللحم والخضار",
    carb: 14,
    qty: "٢٠٠ مل",
  },
  {
    id: "e84tRvfruGV3FTuw8F4K",
    qty: "ثلاث أرباع كأس",
    carb: 15,
    tags: ["الفواكه"],
    item: "التوت الأسود",
  },
  {
    id: "e8zPj0Yaz9Ujy733y9qf",
    item: "ذرة",
    carb: 15,
    tags: ["الخضر النشوية"],
    qty: "ثمرة متوسطة (½ كوب)",
  },
  {
    id: "eLxj610pSGZk9h1AuVyr",
    item: "يغمش",
    carb: 15,
    qty: "٣ قطع",
    tags: [],
  },
  {
    id: "fYliJ21pUjjmj4UjmrZw",
    carb: 15,
    qty: "رغيف",
    tags: ["الخبز والنشويات"],
    item: "تورتيلا صغير",
  },
  {
    id: "fda2xh22opER0v2TLHO6",
    carb: 25,
    tags: ["الأرز والمعكرونة"],
    item: "كبسة",
    qty: "٦ ملاعق",
  },
  {
    id: "feJokmAs6c1Jbs5d1BnS",
    qty: "قطعة واحدة",
    tags: [],
    item: "غولاش",
    carb: 7.52,
  },
  {
    id: "flhFyuu4AU9WzH6Ez1g3",
    carb: 12,
    item: "حليب قليل الدسم",
    tags: [],
    qty: "كوب ٢٤٠ مل",
  },
  {
    id: "g379mQyIIOuWx3GjZYqq",
    carb: 15,
    item: "تين مجفف",
    qty: "ثمرة ونصف",
    tags: ["الفواكه", "المربى"],
  },
  {
    id: "gTSRDIQ4dhg3lChkiKoC",
    qty: "موزة كبيرة / موزة صغيرة ½",
    item: "موز",
    tags: [],
    carb: 15,
  },
  {
    id: "gVJE1QS2uuOqEDKIB0dC",
    qty: "ثلاث أرباع كوب",
    carb: 15,
    tags: ["الحليب ومشتقاته"],
    item: "لبن عادي",
  },
  {
    id: "gflWB6mDeoawt4YskTwF",
    carb: 15,
    item: "أصابع السمك المغطاة بالقماط",
    tags: [],
    qty: "٣ قطع",
  },
  {
    id: "giKrP2l3jUi5myEoe4OV",
    qty: "٢٠٠ مل",
    carb: 9,
    tags: ["أصواص المكرونة"],
    item: "الفرنسية بالبصل",
  },
  {
    id: "gnyCb4YtIGKmREvtEib1",
    tags: [],
    carb: 24,
    item: "مالتيزرز",
    qty: "١٨ حبة",
  },
  {
    id: "gpGoCWjpr0E9CBkYToFY",
    item: "مانجو",
    tags: [],
    qty: "½ كوب",
    carb: 15,
  },
  {
    id: "gqm2a7fo32h1ySQcomJY",
    carb: 15,
    tags: [],
    qty: "شريحتان متوسطتان",
    item: "بانكيك",
  },
  {
    id: "h4H90yqXq2ajledHSfhG",
    tags: ["عُدّ 3 مرات"],
    carb: 3,
    qty: "ملعقة طعام (١٥ غرام)",
    item: "كاتشب",
  },
  {
    id: "h5SOu7obe0qQpF9AZ7jC",
    tags: [],
    item: "كابتشينو",
    carb: 5,
    qty: "كوب (٢٤٠ مل)",
  },
  {
    id: "h5lvIUJGhrVZz8bI4M8c",
    item: "أفوكادو",
    qty: "ثمرة وربع",
    carb: 15,
    tags: ["الفواكه", "المربى"],
  },
  {
    id: "hJQ8OcLsRWj2xkjKpCbp",
    tags: ["الأرز والمعكرونة"],
    qty: "نصف كأس",
    carb: 18,
    item: "اللازانيا",
  },
  {
    id: "hPRVBvq2VDjQ56HZiC6e",
    item: "خبز أسمر",
    carb: 15,
    qty: "شريحة",
    tags: ["الخبز والنشويات"],
  },
  {
    id: "hWYCAPt8eV5ohyNMSOGq",
    item: "كيك موز",
    carb: 40,
    tags: ["الحلويات والكيك"],
    qty: "وصلة واحدة متوسطة",
  },
  {
    id: "hpQmlwpLMPbHXTy717ML",
    item: "مشمش معلب",
    qty: "نصف كوب",
    tags: ["الفواكه"],
    carb: 15,
  },
  {
    id: "hruiScOmZjFxOAcfsU33",
    item: "جريب فروت (قطع، معلب)",
    qty: "ثلاث أرباع كأس",
    carb: 15,
    tags: ["الفواكه"],
  },
  {
    id: "iCOJ9fjWS735pWObtntn",
    carb: 27,
    item: "برياني",
    tags: ["الأرز والمعكرونة"],
    qty: "٦ ملاعق",
  },
  {
    id: "iUI81XHkpIkXFUEuTA1V",
    carb: 23,
    item: "كرواسون لوزين سادة",
    qty: "قطعة واحدة",
    tags: [],
  },
  {
    id: "ieIw0DjiIugw9073Tk2P",
    tags: ["الحلويات والكيك"],
    carb: 15,
    qty: "٥",
    item: "بسكويت الفانيلا الوافر",
  },
  {
    id: "igVMQ5ax5MRLIl7NMtkK",
    qty: "٤ ملاعق طعام",
    item: "سمسم",
    carb: 15,
    tags: ["الوجبات الخفيفة والمكسرات"],
  },
  {
    id: "jFz9j4X65fnWuRwsdXHK",
    qty: "ثلث كأس",
    item: "الفاصولياء (بيضاء، سوداء، بينتو)",
    tags: ["البقوليات"],
    carb: 15,
  },
  {
    id: "jJ38hNAEpMtBVVTvKkFh",
    carb: 50,
    qty: "ربع كوب",
    tags: ["الحلويات والكيك"],
    item: "سكر",
  },
  {
    id: "jKI3uYspMr5hVP6ECnvm",
    carb: 20,
    qty: "نصف كأس",
    item: "حمص",
    tags: ["البقوليات"],
  },
  {
    id: "jOjHcn4bvOBWL2W3JmUP",
    carb: 54,
    item: "الأرز الطويل",
    qty: "كأس واحدة",
    tags: ["الأرز والمعكرونة"],
  },
  {
    id: "jcIPEfjnx6T0Ix6l22dB",
    tags: ["الفواكه"],
    item: "فراولة",
    qty: "٦ ثمرات = ١ ك وربع",
    carb: 15,
  },
  {
    id: "jd1jzL5UJgjcigSl5iqc",
    tags: ["الخبز والنشويات"],
    item: "خبز مدور صغير",
    carb: 15,
    qty: "نصف",
  },
  {
    id: "jfDnWg3Vyzpyk6uALNRG",
    tags: ["العصائر والمشروبات"],
    item: "عصير الجريب فروت",
    carb: 15,
    qty: "نصف كأس",
  },
  {
    id: "jqNkbwNSvp3bjBwAZzdi",
    qty: "كأس واحدة",
    tags: ["الحليب ومشتقاته"],
    carb: 45,
    item: "زبادي قليل الدسم بالفاكهة",
  },
  {
    id: "k597WPYAwHQ4s4woA7eL",
    carb: 0,
    tags: [],
    item: "بيبسي دايت",
    qty: "علبة (٣٥٥ مل)",
  },
  {
    id: "kBvkO2rIQ1qizyXGXtYX",
    item: "كرز",
    tags: ["الفواكه"],
    qty: "١٢ حبة",
    carb: 15,
  },
  {
    id: "kKNHV0t5kLauadd41D0a",
    carb: 21,
    item: "أوريز",
    tags: ["الحلويات والكيك"],
    qty: "٣ قطع",
  },
  {
    id: "kNkMolRzG2Re0Pz7VMVe",
    tags: [],
    item: "بابايا",
    carb: 15,
    qty: "½ ثمرة",
  },
  {
    id: "kfTHXvOGI784eYqjypLG",
    carb: 23,
    qty: "قطعة متوسطة",
    tags: [],
    item: "دونات سادة",
  },
  {
    id: "kmJ2Q4qRiNDJykJ7Q60v",
    qty: "½ رغيف",
    tags: [],
    item: "خبز شامي",
    carb: 15,
  },
  {
    id: "kt05sCOHvDOnjBbUN15U",
    tags: [],
    qty: "قطعة واحدة",
    carb: 39,
    item: "باتيه برانش بالجبن الأبيض",
  },
  {
    id: "l09tPEepCo5ifUBcwfjV",
    qty: "١٠٠غ",
    item: "شيبس",
    carb: 53,
    tags: [],
  },
  {
    id: "l0NNA9fJHFdWTuWpAbVg",
    qty: "قطعة صغيرة",
    item: "كوكيس شوكولاتة",
    tags: ["الحلويات والكيك"],
    carb: 5,
  },
  {
    id: "l2BvjNo2dX7x8J0YrIZR",
    item: "تمر",
    qty: "حبتان",
    carb: 15,
    tags: ["الفواكه", "المربى"],
  },
  {
    id: "lBG2IhGHZeDgVYG3YBjH",
    tags: [],
    item: "لاتيه",
    carb: 12,
    qty: "ظرف واحد",
  },
  {
    id: "lMhzE1yePs8ixUtSPUag",
    item: "كمثرى",
    carb: 15,
    tags: [],
    qty: "ثمرة صغيرة",
  },
  {
    id: "lO3uGBOAbHhRhaiVSQJc",
    item: "بازلاء",
    tags: [],
    carb: 15,
    qty: "½ كوب",
  },
  {
    id: "ldVCtuDNryEJ41mg1rDt",
    item: "مخلل الملفوف",
    qty: "نصف كوب مطبوخ أو كوب واحد غير مطبوخ",
    carb: 5,
    tags: ["الخضر غير النشوية"],
  },
  {
    id: "lhREGHvUIuuDKxRc9vLn",
    tags: [],
    qty: "خبز عربي مفرود صغير",
    carb: 20,
    item: "ساندويتش فلافل صغير",
  },
  {
    id: "ltpqgX8iIquHxY9sVA7o",
    item: "منتو",
    carb: 15,
    tags: [],
    qty: "٣ قطع",
  },
  {
    id: "mG36bIg8jAi3i9aUX4gH",
    qty: "ثمرة متوسطة",
    item: "التفاح",
    tags: ["الفواكه"],
    carb: 20,
  },
  {
    id: "mLYUGFIoo8gsJRipSdHI",
    item: "المافن الإنجليزي",
    tags: ["الحلويات والكيك"],
    carb: 15,
    qty: "نصف قطعة",
  },
  {
    id: "msyZEleZrjgWGOSzjFea",
    item: "المشروب الرياضي",
    tags: ["العصائر والمشروبات"],
    carb: 15,
    qty: "كوب واحد",
  },
  {
    id: "nCx2tRw3uO5O89IZrLDA",
    carb: 15,
    tags: ["الحليب ومشتقاته"],
    item: "زبادي قليل الدسم بالفاكهة",
    qty: "ثلث كأس",
  },
  {
    id: "nFReiibVd2mutWLERyu9",
    tags: [],
    qty: "",
    carb: 9,
    item: "سلطة سيزر بالدجاج",
  },
  {
    id: "nNCxStOjIqXkS2y0Y6fr",
    item: "جزر",
    tags: ["الخضر غير النشوية"],
    qty: "نصف كوب مطبوخ أو كوب واحد غير مطبوخ",
    carb: 5,
  },
  {
    id: "nOZ4EkfTmQvGn7pj18IP",
    tags: [],
    item: "قهوة",
    carb: 0,
    qty: "كوب (١٢٠ مل)",
  },
  {
    id: "njWFOtM05T2MRLIeOn4L",
    carb: 5,
    tags: ["الخضر غير النشوية"],
    qty: "نصف كوب مطبوخ أو كوب واحد غير مطبوخ",
    item: "طماطم (معلب / صلصة صغير)",
  },
  {
    id: "nzrVSamkYc8zRN4nXGjW",
    item: "جريش",
    tags: ["الأرز والمعكرونة"],
    carb: 11,
    qty: "٦ ملاعق طعام",
  },
  {
    id: "oD31JV2XTtyw2nHFJprF",
    qty: "كأس واحدة",
    carb: 46,
    item: "البر",
    tags: ["الأرز والمعكرونة"],
  },
  {
    id: "oHzWvhYjL6TCWSVCCELV",
    tags: ["البقوليات"],
    qty: "ربع كأس",
    carb: 15,
    item: "الجرانولا - قليل الدسم",
  },
  {
    id: "oXtFHTC3Ye5k646c8D17",
    item: "كيك شوكولاتة",
    tags: ["الحلويات والكيك"],
    qty: "٦٥ غرام = ثمن كيك كبير = ٢ اونس",
    carb: 24,
  },
  {
    id: "okNL5hnnMpV6pNvS6lH6",
    qty: "ثمرة واحدة",
    tags: ["الفواكه"],
    item: "كيوي، دون قشر",
    carb: 10,
  },
  {
    id: "onqPGQk0O9vLDsrUtr1n",
    qty: "قطعة متوسطة",
    tags: [],
    item: "تشيز كيك",
    carb: 20,
  },
  {
    id: "opC8mCLeGYBsaKmAZygp",
    qty: "١٠٠ غم",
    tags: ["البقوليات"],
    carb: 75,
    item: "الطحين",
  },
  {
    id: "oxBDMI4ACUyeLow48KYZ",
    tags: ["الحليب ومشتقاته"],
    item: "حليب مكثف",
    qty: "نصف كوب",
    carb: 15,
  },
  {
    id: "pAbjXeeKHsLD8MGHHwJu",
    qty: "قطعة صدر",
    tags: [],
    item: "بروست دجاج",
    carb: 13,
  },
  {
    id: "pG9YtSJxIaJ8V0HXFc2d",
    tags: ["الحليب ومشتقاته"],
    qty: "ثلث كوب",
    carb: 15,
    item: "حليب مجفف",
  },
  {
    id: "pHDddvSSwic54KiLntHd",
    carb: 33,
    tags: ["الحلويات والكيك"],
    item: "دونت سادة مدور",
    qty: "قطعة واحدة",
  },
  {
    id: "pIm9qc9bjyWlP5Yi7vRG",
    item: "تورتيلا كبير",
    qty: "رغيف - حجم الفاهيتا",
    carb: 30,
    tags: ["الخبز والنشويات"],
  },
  {
    id: "pKsIht6Y45OyGiFz5Nfx",
    item: "خبز هامبورجر - هاتدوق",
    tags: ["الخبز والنشويات"],
    carb: 15,
    qty: "نصف",
  },
  {
    id: "pdCEvhiq3qgP2JPw7x73",
    carb: 15,
    tags: ["الحبوب"],
    qty: "نصف كأس",
    item: "الحبوب المطبوخة",
  },
  {
    id: "pj1HG0JT22y3r7XrsNtI",
    item: "كرنب",
    tags: ["الخضر غير النشوية"],
    qty: "نصف كوب مطبوخ أو كوب واحد غير مطبوخ",
    carb: 5,
  },
  {
    id: "q3cvoR8gamU9ZqbNkLWP",
    carb: 30,
    qty: "كوب واحد",
    tags: ["الأرز والمعكرونة"],
    item: "سلطة معكرونة",
  },
  {
    id: "q9WPdzjRyxI1qkZmRWvI",
    tags: ["الأرز والمعكرونة"],
    qty: "٧ ملاعق",
    item: "سليق",
    carb: 15,
  },
  {
    id: "qHUfw8bYR8DGuQ6Sa0kX",
    qty: "٣ ملاعق شاهي",
    carb: 4,
    tags: ["البقوليات"],
    item: "بايكين باودر",
  },
  {
    id: "qVYVyIjmAtvf1A75TC40",
    item: "ذرة مطبوخة",
    carb: 15,
    qty: "ثلث كوب",
    tags: ["الخضر النشوية"],
  },
  {
    id: "qdOxWJCOAu2YicqEmyeR",
    carb: 13,
    item: "تركس",
    qty: "نصف كأس",
    tags: ["الحبوب"],
  },
  {
    id: "qmUPBVNJMDi62hx1Y6jT",
    qty: "نصف كوب = ١ مغرفة",
    carb: 15,
    tags: ["الحليب ومشتقاته"],
    item: "آيس كريم",
  },
  {
    id: "quLrlzyrEkKwUhjHehkg",
    item: "كوكيز",
    tags: ["الحلويات والكيك"],
    qty: "قطعة واحدة بحجم ٣ بوصات بالعرض",
    carb: 15,
  },
  {
    id: "qyzPWvm9pqyjWesUrFnj",
    tags: ["العصائر والمشروبات"],
    qty: "ظرف واحد",
    item: "شراب الكاكاو بدون سكر",
    carb: 7,
  },
  {
    id: "qzTprRS4BGm6egkBvYeo",
    carb: 25,
    tags: [],
    qty: "قطعة متوسطة",
    item: "وافل",
  },
  {
    id: "rLCzIYV4ABjxVwJ2lZ9C",
    qty: "٣ حبات (٢ ونصف بوصة مربعة)",
    tags: ["الوجبات الخفيفة والمكسرات"],
    carb: 15,
    item: "مكسرات جراهام",
  },
  {
    id: "rh7pHZ94SIJzAxxKml1R",
    tags: ["الحلويات والكيك"],
    item: "كيك بالجزر",
    carb: 22,
    qty: "٢ اونس",
  },
  {
    id: "rhEWwS3lbvtRU2nzoqw8",
    carb: 21.4,
    tags: [],
    qty: "شطيرة واحدة ١٠٠ غرام",
    item: "كريب دجاج",
  },
  {
    id: "rmXW1odXSuvG8H2hBVCl",
    carb: 10,
    qty: "ربع كوب",
    item: "صوص السلطة العادي",
    tags: ["الصلصات - الأصواص - الشوربات"],
  },
  {
    id: "s1YR6XMwy55VychEFabL",
    qty: "٣ عود",
    carb: 1,
    item: "باذنجان",
    tags: [],
  },
  {
    id: "s4N7rR1VwnvY4VTacjuZ",
    tags: ["الأرز والمعكرونة"],
    item: "الأرز",
    carb: 15,
    qty: "ثلث كأس",
  },
  {
    id: "sD04JQ9r1WbC8f6FMvU6",
    item: "الدقيق الجاف",
    qty: "٣ ملاعق طعام",
    carb: 15,
    tags: ["البقوليات"],
  },
  {
    id: "sEUMksC56r7UdIdPgdi4",
    carb: 30,
    item: "فطيرة قرع أو كاسترد",
    qty: "ثمن فطيرة",
    tags: ["الخبز والنشويات"],
  },
  {
    id: "sHmx5MrAvFyv4sJ9cFbP",
    item: "بطاطس مهروس",
    tags: ["الخضر النشوية"],
    carb: 15,
    qty: "نصف كأس",
  },
  {
    id: "sMyU5KcyCwF0vaLXRvDn",
    qty: "كوب",
    carb: 156,
    tags: [],
    item: "أرز بسمتي",
  },
  {
    id: "sSz6j5Ks9o3WIgXXbjRC",
    qty: "قطعة واحدة",
    tags: [],
    item: "فطيرة لوزين بالتفاح",
    carb: 27,
  },
  {
    id: "sZn1i8pbmlObjtZLhUCL",
    item: "قرع شتوي",
    qty: "كأس واحدة",
    carb: 22,
    tags: ["الخضر النشوية"],
  },
  {
    id: "sjJxtLvSuO7g2r7milRh",
    item: "مطبق",
    qty: "٢-٣ قطع",
    carb: 15,
    tags: [],
  },
  {
    id: "soooF3OUqnv47WTpWN7l",
    qty: "كأس واحدة",
    tags: ["الأرز والمعكرونة"],
    item: "السوشي",
    carb: 96,
  },
  {
    id: "tDJJvtfXRluFAZhhkVSL",
    qty: "ثلاث أرباع كوب",
    tags: ["الحليب ومشتقاته"],
    item: "لبن قليل الدسم",
    carb: 15,
  },
  {
    id: "tdBCotdzHKr9nQH9Te3Q",
    qty: "٢٥ غم",
    carb: 20,
    tags: ["البقوليات"],
    item: "دقيق الذرة",
  },
  {
    id: "trjQlKEp1korakl64jmV",
    qty: "ملعقة طعام (١٥ غرام)",
    item: "مايونيز",
    carb: 3,
    tags: [],
  },
  {
    id: "u0nDnylTwCabY2mVS50e",
    tags: ["الفواكه", "المربى"],
    item: "فواكه مشكلة - معلبة",
    qty: "نصف كوب",
    carb: 15,
  },
  {
    id: "u5BhWgu2jNIPOFNCm5c1",
    qty: "كأس واحدة",
    item: "زبادي منزوع الدسم",
    carb: 15,
    tags: ["الحليب ومشتقاته"],
  },
  {
    id: "uKlVzZFEx1DdKR0G1ToF",
    tags: ["الوجبات الخفيفة والمكسرات"],
    carb: 30,
    item: "ساندوتش لحم أو جبن",
    qty: "شطيرة واحدة",
  },
  {
    id: "uRI5kI0OO0Wv6kIo8LTL",
    tags: ["الحليب ومشتقاته"],
    qty: "كوب واحد",
    item: "آيس كريم شوكولاتة (شيربيرت)",
    carb: 30,
  },
  {
    id: "uRh9X63OjDe7wufyGm2z",
    qty: "¾ كوب",
    item: "كورن فلكس بالفواكه",
    tags: [],
    carb: 24,
  },
  {
    id: "ujC8A1QVi9QRpiEWI2jP",
    carb: 9,
    tags: [],
    qty: "٢٠٠ مل",
    item: "شوربة البصل الفرنسية",
  },
  {
    id: "um2jgZXHGIVqiyWnjLKj",
    item: "برقوق",
    tags: [],
    carb: 15,
    qty: "ثمرتان",
  },
  {
    id: "umfNY8txLfTR4wshVDRJ",
    qty: "نصف كأس",
    carb: 15,
    item: "صلصة التفاح",
    tags: ["الفواكه"],
  },
  {
    id: "uqtIYJii5bSiGjx8jfxv",
    carb: 14,
    item: "اللحم والخضر",
    qty: "٢٠٠ مل",
    tags: [],
  },
  {
    id: "v6WjqxU1PEHwCAdz5DTH",
    tags: [],
    item: "كشري",
    qty: "علبة كبيرة",
    carb: 141,
  },
  {
    id: "v7UFR3lV5RB8SEbWTkO2",
    item: "بران بالزبيب",
    qty: "ثلث كأس",
    tags: ["الحبوب"],
    carb: 15,
  },
  {
    id: "vI2D0fMkuiGGf3wvmPqC",
    carb: 5,
    qty: "نصف كوب مطبوخ أو كوب واحد غير مطبوخ",
    item: "سلطة خضراء",
    tags: ["الخضر غير النشوية"],
  },
  {
    id: "vLpnKhq5Uwnd2Fch7Qp5",
    tags: ["الفواكه"],
    qty: "نصف كأس",
    item: "كمثرى معلب",
    carb: 15,
  },
  {
    id: "vRRjWsUjbhHsBSlvE9ju",
    carb: 23,
    tags: ["الحلويات والكيك"],
    qty: "نصف كوب",
    item: "حلوى البودينج",
  },
  {
    id: "vs3at6spGngu6vz9q5PV",
    carb: 15,
    item: "أناناس طازج",
    qty: "ثلاثة أرباع",
    tags: ["الفواكه"],
  },
  {
    id: "w7RgkTRBbckxwIdGJ7dC",
    carb: 30,
    tags: [],
    qty: "قطعة واحدة",
    item: "فطيرة لوزين بالشوكولاتة",
  },
  {
    id: "w80lax9O3t7HVSy6tRVY",
    carb: 15,
    tags: ["الخضر النشوية"],
    item: "جوز",
    qty: "كأس واحدة",
  },
  {
    id: "wJXWjcqNVMMliFJvogc7",
    item: "كت كات",
    carb: 13,
    qty: "إصبعان",
    tags: [],
  },
  {
    id: "wPXtdIK9tTNq0XSi4AYz",
    carb: 48,
    tags: [],
    item: "مولتو كرواسون",
    qty: "قطعة واحدة",
  },
  {
    id: "wsTq0vQfD3dwLwfKsdgQ",
    item: "بطاطس مهروسة",
    tags: [],
    qty: "½ كوب",
    carb: 15,
  },
  {
    id: "wt2QX137l5ojwF6cQLF6",
    item: "فلافل",
    tags: [],
    qty: "٣ أقراص",
    carb: 15,
  },
  {
    id: "wtYc4dPYi1u1wkX8XUYr",
    carb: 12,
    tags: [],
    qty: "كوب ٢٤٠ مل",
    item: "حليب كامل الدسم",
  },
  {
    id: "x6hLqb0Z5sOIQlXOv8Dp",
    qty: "٦ ملاعق",
    carb: 28,
    item: "مراصيع",
    tags: ["الأرز والمعكرونة"],
  },
  {
    id: "xJsANpX99R05khqeU2kF",
    tags: ["الحلويات والكيك"],
    carb: 15,
    item: "شيره خفيفة",
    qty: "ملعقتان كبيرتان",
  },
  {
    id: "xOOIzYAKPhUHTVoX2J5g",
    carb: 15,
    tags: [],
    qty: "ملعقة طعام",
    item: "مربى",
  },
  {
    id: "xVJQBezm0WaxpfYknpoT",
    qty: "٣ ثمرات متوسطة",
    tags: ["الفواكه", "المربى"],
    item: "بخارى مجففة",
    carb: 15,
  },
  {
    id: "xe5XwZpXPqMjQbNfIUB0",
    item: "طحين",
    qty: "ملعقة طعام",
    carb: 3,
    tags: [],
  },
  {
    id: "xgTbrnBucwdcTufoqOKW",
    qty: "¾ كوب",
    carb: 15,
    tags: [],
    item: "توت أزرق",
  },
  {
    id: "xnteVgFvDYWhdIMcyA4o",
    tags: ["الخبز والنشويات"],
    item: "خبز فرنسي محمص",
    qty: "شريحة واحدة",
    carb: 15,
  },
  {
    id: "xx41unMjdHgpYxLj7PAM",
    carb: 15,
    tags: ["الفواكه"],
    item: "خوخ معلب",
    qty: "نصف كأس",
  },
  {
    id: "y7xojprRU4uRYuTZDKU0",
    carb: 0,
    tags: [],
    item: "شاي",
    qty: "كوب (١٢٠ مل)",
  },
  {
    id: "yDuzwEL3VKwSubBXcxzL",
    qty: "كوب (١٧٠ غرام) ½",
    item: "لبن روب زبادي",
    tags: [],
    carb: 12,
  },
  {
    id: "yOZzC97V4DM5GRXB5fTE",
    item: "كراكرز بالجبن",
    qty: "٤ حبات",
    carb: 8,
    tags: ["الخبز والنشويات"],
  },
  {
    id: "yVlWCx5lTufo0g1dqdaz",
    tags: ["الخضر غير النشوية"],
    item: "كرفس",
    carb: 5,
    qty: "نصف كوب مطبوخ أو كوب واحد غير مطبوخ",
  },
  {
    id: "yWkN2kstJmsZe89rdXvu",
    qty: "٦-٨ ملاعق طعام",
    carb: 15,
    item: "فول",
    tags: [],
  },
  {
    id: "yaLbfCqlaFMwwCGhFRuJ",
    qty: "إصبع واحد",
    item: "محشي كرنب",
    carb: 8,
    tags: [],
  },
  {
    id: "ybl5zMrNdg9TCJfnPa7z",
    carb: 15,
    tags: [],
    item: "كيك",
    qty: "قطعة متوسطة",
  },
  {
    id: "yel7TNv1G3gBpZs4P3cY",
    item: "ترمس",
    tags: [],
    qty: "كوب",
    carb: 15,
  },
  {
    id: "yfDmMDkKKAhINSkzCYSA",
    qty: "نصف كوب مطبوخ أو كوب واحد غير مطبوخ",
    item: "بنجر مطهو",
    carb: 5,
    tags: ["الخضر غير النشوية"],
  },
  {
    id: "yl0gt6CHuwfFBE1JJIY1",
    tags: [],
    qty: "٤ - ٦ حبات",
    carb: 15,
    item: "بسكويت مملح",
  },
  {
    id: "yqgb33bMLwI182MdOJ5n",
    tags: ["الخضر النشوية"],
    qty: "كأس واحدة",
    item: "بلوط",
    carb: 15,
  },
  {
    id: "zTIpGRKQjHMnnwtodQyn",
    qty: "نصف كوب مطبوخ أو كوب واحد غير مطبوخ",
    item: "هليون",
    tags: ["الخضر غير النشوية"],
    carb: 5,
  },
  {
    id: "zWPtp4ok2XXImFBTmcHN",
    carb: 25,
    item: "كت كات تشونكي",
    qty: "قطعة",
    tags: [],
  },
  {
    id: "zYgnQHzYFSIDnCSRlrlk",
    item: "جريب فروت",
    tags: [],
    qty: "½ ثمرة",
    carb: 15,
  },
  {
    id: "zfFnH92AtvaCKRWVHTJD",
    item: "حمص",
    tags: [],
    carb: 15,
    qty: "كوب (٥ ملاعق طعام) ¼",
  },
  {
    id: "zitdi81124H4iSCu7YPl",
    qty: "ربع",
    tags: ["الخبز والنشويات"],
    carb: 15,
    item: "خبز عربي متوسط",
  },
  {
    id: "zuYkJyeWvbIV6TMtfiKR",
    tags: ["الحلويات والكيك"],
    qty: "حبة",
    carb: 10,
    item: "البسكويت المهضم",
  },
  {
    id: "zwbgBDgaLEvtfV1qmziX",
    tags: ["الخضر غير النشوية"],
    item: "فطريات",
    qty: "نصف كوب مطبوخ أو كوب واحد غير مطبوخ",
    carb: 5,
  },
];
